name: created_by_618_abdo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # Ensure Dart SDK version is 3.5.0 or newer

dependencies:
  flutter:
    sdk: flutter
    # Add this line for email validation

  # Specify dependencies versions
  gsheets: ^0.5.0
  intl_phone_field: ^3.2.0
  intl: ^0.17.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  googleapis: ^11.4.0
  googleapis_auth: ^1.6.0
  file_picker: ^10.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.1.4
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  mobile_scanner: ^6.0.2
  cached_network_image: ^3.2.0
  email_validator: ^2.0.1 # Add this line for email validation
  image: ^4.3.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  tflite_flutter: ^0.11.0
  sqflite: ^2.4.1
  camera: ^0.10.5+9
  supabase_flutter: ^2.8.4
  http: any
  flutter_screenutil: any
  url_launcher: any
  flutter_dotenv: ^5.2.1
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^5.0.9
  url_launcher: ^6.0.17
  url_launcher_web: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_screenutil: ^5.9.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/logo.png
    - assets/credentials.json
    - .env
